In [1]:
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt
import seaborn as sns
%matplotlib inline

In [3]:
from sklearn.datasets import load_breast_cancer

In [7]:
cancer=load_breast_cancer()

In [8]:
cancer.keys()

dict_keys(['data', 'target', 'target_names', 'DESCR', 'feature_names', 'filename'])

In [9]:
print(cancer['DESCR'])

.. _breast_cancer_dataset:

Breast cancer wisconsin (diagnostic) dataset
--------------------------------------------

**Data Set Characteristics:**

    :Number of Instances: 569

    :Number of Attributes: 30 numeric, predictive attributes and the class

    :Attribute Information:
        - radius (mean of distances from center to points on the perimeter)
        - texture (standard deviation of gray-scale values)
        - perimeter
        - area
        - smoothness (local variation in radius lengths)
        - compactness (perimeter^2 / area - 1.0)
        - concavity (severity of concave portions of the contour)
        - concave points (number of concave portions of the contour)
        - symmetry 
        - fractal dimension ("coastline approximation" - 1)

        The mean, standard error, and "worst" or largest (mean of the three
        largest values) of these features were computed for each image,
        resulting in 30 features.  For instance, field 3 is Mean Radius, f

In [10]:
print(cancer['target'])

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 1 0 0 0 0 0 0 0 0 1 0 1 1 1 1 1 0 0 1 0 0 1 1 1 1 0 1 0 0 1 1 1 1 0 1 0 0
 1 0 1 0 0 1 1 1 0 0 1 0 0 0 1 1 1 0 1 1 0 0 1 1 1 0 0 1 1 1 1 0 1 1 0 1 1
 1 1 1 1 1 1 0 0 0 1 0 0 1 1 1 0 0 1 0 1 0 0 1 0 0 1 1 0 1 1 0 1 1 1 1 0 1
 1 1 1 1 1 1 1 1 0 1 1 1 1 0 0 1 0 1 1 0 0 1 1 0 0 1 1 1 1 0 1 1 0 0 0 1 0
 1 0 1 1 1 0 1 1 0 0 1 0 0 0 0 1 0 0 0 1 0 1 0 1 1 0 1 0 0 0 0 1 1 0 0 1 1
 1 0 1 1 1 1 1 0 0 1 1 0 1 1 0 0 1 0 1 1 1 1 0 1 1 1 1 1 0 1 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 1 1 1 1 1 1 0 1 0 1 1 0 1 1 0 1 0 0 1 1 1 1 1 1 1 1 1 1 1 1
 1 0 1 1 0 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 0 1 0 1 1 1 1 0 0 0 1 1
 1 1 0 1 0 1 0 1 1 1 0 1 1 1 1 1 1 1 0 0 0 1 1 1 1 1 1 1 1 1 1 1 0 0 1 0 0
 0 1 0 0 1 1 1 1 1 0 1 1 1 1 1 0 1 1 1 0 1 1 0 0 1 1 1 1 1 1 0 1 1 1 1 1 1
 1 0 1 1 1 1 1 0 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 0 1 0 0 1 0 1 1 1 1 1 0 1 1
 0 1 0 1 1 0 1 0 1 1 1 1 1 1 1 1 0 0 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 0 1
 1 1 1 1 1 1 0 1 0 1 1 0 

In [11]:
print(cancer['target_names'])

['malignant' 'benign']


In [12]:
print(cancer['data'])

[[1.799e+01 1.038e+01 1.228e+02 ... 2.654e-01 4.601e-01 1.189e-01]
 [2.057e+01 1.777e+01 1.329e+02 ... 1.860e-01 2.750e-01 8.902e-02]
 [1.969e+01 2.125e+01 1.300e+02 ... 2.430e-01 3.613e-01 8.758e-02]
 ...
 [1.660e+01 2.808e+01 1.083e+02 ... 1.418e-01 2.218e-01 7.820e-02]
 [2.060e+01 2.933e+01 1.401e+02 ... 2.650e-01 4.087e-01 1.240e-01]
 [7.760e+00 2.454e+01 4.792e+01 ... 0.000e+00 2.871e-01 7.039e-02]]


In [13]:
df_feat = pd.DataFrame(cancer['data'],columns=cancer['feature_names'])

In [14]:
df_feat.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 30 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   mean radius              569 non-null    float64
 1   mean texture             569 non-null    float64
 2   mean perimeter           569 non-null    float64
 3   mean area                569 non-null    float64
 4   mean smoothness          569 non-null    float64
 5   mean compactness         569 non-null    float64
 6   mean concavity           569 non-null    float64
 7   mean concave points      569 non-null    float64
 8   mean symmetry            569 non-null    float64
 9   mean fractal dimension   569 non-null    float64
 10  radius error             569 non-null    float64
 11  texture error            569 non-null    float64
 12  perimeter error          569 non-null    float64
 13  area error               569 non-null    float64
 14  smoothness error         5

In [15]:
cancer['target']

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0,
       0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0,

In [20]:
df_target=pd.DataFrame(cancer['target'],columns=['cancer'])

In [63]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(df_feat,np.ravel(df_target),test_size=0.20)

In [64]:
x_train

mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
269       10.710         20.39           69.50      344.9          0.10820   
556       10.160         19.59           64.73      311.7          0.10030   
63         9.173         13.86           59.20      260.9          0.07721   
557        9.423         27.88           59.26      271.3          0.08123   
304       11.460         18.16           73.59      403.1          0.08853   
..           ...           ...             ...        ...              ...   
225       14.340         13.47           92.51      641.2          0.09906   
16        14.680         20.13           94.74      684.5          0.09867   
55        11.520         18.75           73.34      409.0          0.09524   
199       14.450         20.22           94.49      642.7          0.09872   
394       12.100         17.72           78.07      446.2          0.10290   

     mean compactness  mean concavity  mean concave points  mean symmetry  \
269           0.12890        0.084480              0.02867         0.1668   
556           0.07504        0.005025              0.01116         0.1791   
63            0.08751        0.059880              0.02180         0.2341   
557           0.04971        0.000000              0.00000         0.1742   
304           0.07694        0.033440              0.01502         0.1411   
..                ...             ...                  ...            ...   
225           0.07624        0.057240              0.04603         0.2075   
16            0.07200        0.073950              0.05259         0.1586   
55            0.05473        0.030360              0.02278         0.1920   
199           0.12060        0.118000              0.05980         0.1950   
394           0.09758        0.047830              0.03326         0.1937   

     mean fractal dimension  ...  worst radius  worst texture  \
269                 0.06862  ...         11.69          25.21   
556                 0.06331  ...         10.65          22.88   
63                  0.06963  ...         10.01          19.23   
557                 0.06059  ...         10.49          34.24   
304                 0.06243  ...         12.68          21.61   
..                      ...  ...           ...            ...   
225                 0.05448  ...         16.77          16.90   
16                  0.05922  ...         19.07          30.88   
55                  0.05907  ...         12.84          22.47   
199                 0.06466  ...         18.33          30.12   
394                 0.06161  ...         13.56          25.80   

     worst perimeter  worst area  worst smoothness  worst compactness  \
269            76.51       410.4           0.13350            0.25500   
556            67.88       347.3           0.12650            0.12000   
63             65.59       310.1           0.09836            0.16780   
557            66.50       330.6           0.10730            0.07158   
304            82.69       489.8           0.11440            0.17890   
..               ...         ...               ...                ...   
225           110.40       873.2           0.12970            0.15250   
16            123.40      1138.0           0.14640            0.18710   
55             81.81       506.2           0.12490            0.08720   
199           117.90      1044.0           0.15520            0.40560   
394            88.33       559.5           0.14320            0.17730   

     worst concavity  worst concave points  worst symmetry  \
269          0.25340               0.08600          0.2605   
556          0.01005               0.02232          0.2262   
63           0.13970               0.05087          0.3282   
557          0.00000               0.00000          0.2475   
304          0.12260               0.05509          0.2208   
..               ...                   ...             ...   
225          0.16320               0.10870         

In [65]:
from sklearn.svm import SVC

In [66]:
model=SVC()

In [67]:
model.fit(x_train,y_train)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [68]:
x_test

mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
419       11.160         21.41           70.95      380.3          0.10180   
132       16.160         21.54          106.20      809.8          0.10080   
441       17.270         25.42          112.40      928.8          0.08331   
27        18.610         20.25          122.10     1094.0          0.09440   
471       12.040         28.14           76.85      449.9          0.08752   
..           ...           ...             ...        ...              ...   
364       13.400         16.95           85.48      552.4          0.07937   
215       13.860         16.93           90.96      578.9          0.10260   
109       11.340         21.26           72.48      396.5          0.08759   
525        8.571         13.10           54.53      221.3          0.10360   
246       13.200         17.43           84.13      541.6          0.07215   

     mean compactness  mean concavity  mean concave points  mean symmetry  \
419           0.05978        0.008955              0.01076         0.1615   
132           0.12840        0.104300              0.05613         0.2160   
441           0.11090        0.120400              0.05736         0.1467   
27            0.10660        0.149000              0.07731         0.1697   
471           0.06000        0.023670              0.02377         0.1854   
..                ...             ...                  ...            ...   
364           0.05696        0.021810              0.01473         0.1650   
215           0.15170        0.099010              0.05602         0.2106   
109           0.06575        0.051330              0.01899         0.1487   
525           0.07632        0.025650              0.01510         0.1678   
246           0.04524        0.043360              0.01105         0.1487   

     mean fractal dimension  ...  worst radius  worst texture  \
419                 0.06144  ...        12.360          28.92   
132                 0.05891  ...        19.470          31.68   
441                 0.05407  ...        20.380          35.46   
27                  0.05699  ...        21.310          27.26   
471                 0.05698  ...        13.600          33.33   
..                      ...  ...           ...            ...   
364                 0.05701  ...        14.730          21.70   
215                 0.06916  ...        15.750          26.93   
109                 0.06529  ...        13.010          29.15   
525                 0.07126  ...         9.473          18.45   
246                 0.05635  ...        13.940          27.82   

     worst perimeter  worst area  worst smoothness  worst compactness  \
419            79.26       458.0            0.1282            0.11080   
132           129.70      1175.0            0.1395            0.30550   
441           132.80      1284.0            0.1436            0.41220   
27            139.90      1403.0            0.1338            0.21170   
471            87.24       567.6            0.1041            0.09726   
..               ...         ...               ...                ...   
364            93.76       663.5            0.1213            0.16760   
215           104.40       750.1            0.1460            0.43700   
109            83.99       518.1            0.1699            0.21960   
525            63.30       275.6            0.1641            0.22350   
246            88.28       602.0            0.1101            0.15080   

     worst concavity  worst concave points  worst symmetry  \
419          0.03582               0.04306          0.2976   
132          0.29920               0.13120          0.3480   
441          0.50360               0.17390          0.2500   
27           0.34460               0.14900          0.2341   
471          0.05524               0.05547          0.2404   
..               ...                   ...             ...   
364          0.13640               0.06987         

In [69]:
model.predict(x_test)

array([1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1,
       0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1,
       0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1,
       1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1,
       1, 1, 1, 1])

In [70]:
y_pred=model.predict(x_test)

In [71]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test,y_pred)

array([[39,  8],
       [ 2, 65]], dtype=int64)

In [72]:
from sklearn.metrics import classification_report

In [73]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.95      0.83      0.89        47
           1       0.89      0.97      0.93        67

    accuracy                           0.91       114
   macro avg       0.92      0.90      0.91       114
weighted avg       0.92      0.91      0.91       114



In [74]:
from sklearn.metrics import accuracy_score
print('Accuracy Score:',accuracy_score(y_test,y_pred))

Accuracy Score: 0.9122807017543859


In [75]:
param_grid={'C':[0.1,1,10,100,1000],'gamma':[0.1,1,10,100,1000],'kernel':['rbf']}

In [76]:
from sklearn.model_selection import GridSearchCV

In [77]:
grid = GridSearchCV(SVC(),param_grid,refit=True, verbose=3)

In [78]:
grid.fit(x_train,y_train)

Fitting 5 folds for each of 25 candidates, totalling 125 fits
[CV] C=0.1, gamma=0.1, kernel=rbf ....................................
[CV] ........ C=0.1, gamma=0.1, kernel=rbf, score=0.637, total=   0.0s
[CV] C=0.1, gamma=0.1, kernel=rbf ....................................
[CV] ........ C=0.1, gamma=0.1, kernel=rbf, score=0.637, total=   0.0s
[CV] C=0.1, gamma=0.1, kernel=rbf ....................................
[CV] ........ C=0.1, gamma=0.1, kernel=rbf, score=0.637, total=   0.0s
[CV] C=0.1, gamma=0.1, kernel=rbf ....................................
[CV] ........ C=0.1, gamma=0.1, kernel=rbf, score=0.637, total=   0.0s
[CV] C=0.1, gamma=0.1, kernel=rbf ....................................
[CV] ........ C=0.1, gamma=0.1, kernel=rbf, score=0.637, total=   0.0s
[CV] C=0.1, gamma=1, kernel=rbf ......................................
[CV] .......... C=0.1, gamma=1, kernel=rbf, score=0.637, total=   0.0s
[CV] C=0.1, gamma=1, kernel=rbf ......................................
[CV] ..........

[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=1)]: Done   2 out of   2 | elapsed:    0.0s remaining:    0.0s


[CV] ......... C=0.1, gamma=10, kernel=rbf, score=0.637, total=   0.0s
[CV] C=0.1, gamma=10, kernel=rbf .....................................
[CV] ......... C=0.1, gamma=10, kernel=rbf, score=0.637, total=   0.0s
[CV] C=0.1, gamma=10, kernel=rbf .....................................
[CV] ......... C=0.1, gamma=10, kernel=rbf, score=0.637, total=   0.0s
[CV] C=0.1, gamma=10, kernel=rbf .....................................
[CV] ......... C=0.1, gamma=10, kernel=rbf, score=0.637, total=   0.0s
[CV] C=0.1, gamma=10, kernel=rbf .....................................
[CV] ......... C=0.1, gamma=10, kernel=rbf, score=0.637, total=   0.0s
[CV] C=0.1, gamma=100, kernel=rbf ....................................
[CV] ........ C=0.1, gamma=100, kernel=rbf, score=0.637, total=   0.0s
[CV] C=0.1, gamma=100, kernel=rbf ....................................
[CV] ........ C=0.1, gamma=100, kernel=rbf, score=0.637, total=   0.0s
[CV] C=0.1, gamma=100, kernel=rbf ....................................
[CV] .

[CV] ........ C=100, gamma=0.1, kernel=rbf, score=0.637, total=   0.0s
[CV] C=100, gamma=0.1, kernel=rbf ....................................
[CV] ........ C=100, gamma=0.1, kernel=rbf, score=0.637, total=   0.0s
[CV] C=100, gamma=1, kernel=rbf ......................................
[CV] .......... C=100, gamma=1, kernel=rbf, score=0.637, total=   0.0s
[CV] C=100, gamma=1, kernel=rbf ......................................
[CV] .......... C=100, gamma=1, kernel=rbf, score=0.637, total=   0.0s
[CV] C=100, gamma=1, kernel=rbf ......................................
[CV] .......... C=100, gamma=1, kernel=rbf, score=0.637, total=   0.0s
[CV] C=100, gamma=1, kernel=rbf ......................................
[CV] .......... C=100, gamma=1, kernel=rbf, score=0.637, total=   0.0s
[CV] C=100, gamma=1, kernel=rbf ......................................
[CV] .......... C=100, gamma=1, kernel=rbf, score=0.637, total=   0.0s
[CV] C=100, gamma=10, kernel=rbf .....................................
[CV] .

[Parallel(n_jobs=1)]: Done 125 out of 125 | elapsed:    2.3s finished


GridSearchCV(cv=None, error_score=nan,
             estimator=SVC(C=1.0, break_ties=False, cache_size=200,
                           class_weight=None, coef0=0.0,
                           decision_function_shape='ovr', degree=3,
                           gamma='scale', kernel='rbf', max_iter=-1,
                           probability=False, random_state=None, shrinking=True,
                           tol=0.001, verbose=False),
             iid='deprecated', n_jobs=None,
             param_grid={'C': [0.1, 1, 10, 100, 1000],
                         'gamma': [0.1, 1, 10, 100, 1000], 'kernel': ['rbf']},
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring=None, verbose=3)

In [79]:
grid.best_params_

{'C': 0.1, 'gamma': 0.1, 'kernel': 'rbf'}

In [80]:
grid.best_estimator_

SVC(C=0.1, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma=0.1, kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [81]:
grid_predictions=grid.predict(x_test)

In [82]:
print(confusion_matrix(y_test,grid_predictions))
print(classification_report(y_test,grid_predictions))

[[ 0 47]
 [ 0 67]]
              precision    recall  f1-score   support

           0       0.00      0.00      0.00        47
           1       0.59      1.00      0.74        67

    accuracy                           0.59       114
   macro avg       0.29      0.50      0.37       114
weighted avg       0.35      0.59      0.44       114



c:\users\tanishka dodiya\appdata\local\programs\python\python38-32\lib\site-packages\sklearn\metrics\_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [83]:
print('Accuracy Score:',accuracy_score(y_test,grid_predictions))

Accuracy Score: 0.5877192982456141
