In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.DataFrame(np.array([5,7,9,np.NaN,np.NaN,np.NaN,-5,0,25,999,1,0,np.NaN,0,np.NaN]).reshape(5,3))

In [3]:
df

0    1     2
0    5.0  7.0   9.0
1    NaN  NaN   NaN
2   -5.0  0.0  25.0
3  999.0  1.0   0.0
4    NaN  0.0   NaN

In [4]:
from sklearn.impute import SimpleImputer

In [5]:
imp = SimpleImputer(missing_values=np.NaN, strategy='mean')
imp.fit_transform(df)

array([[  5.        ,   7.        ,   9.        ],
       [333.        ,   2.        ,  11.33333333],
       [ -5.        ,   0.        ,  25.        ],
       [999.        ,   1.        ,   0.        ],
       [333.        ,   0.        ,  11.33333333]])

In [6]:
imp = SimpleImputer(missing_values=np.NaN, strategy='median')
imp.fit_transform(df)

array([[ 5.00e+00,  7.00e+00,  9.00e+00],
       [ 5.00e+00,  5.00e-01,  9.00e+00],
       [-5.00e+00,  0.00e+00,  2.50e+01],
       [ 9.99e+02,  1.00e+00,  0.00e+00],
       [ 5.00e+00,  0.00e+00,  9.00e+00]])

In [7]:
imp = SimpleImputer(missing_values=np.NaN, strategy='most_frequent')
imp.fit_transform(df)

array([[  5.,   7.,   9.],
       [ -5.,   0.,   0.],
       [ -5.,   0.,  25.],
       [999.,   1.,   0.],
       [ -5.,   0.,   0.]])

In [8]:
imp = SimpleImputer(missing_values=np.NaN, strategy='constant')
imp.fit_transform(df)

array([[  5.,   7.,   9.],
       [  0.,   0.,   0.],
       [ -5.,   0.,  25.],
       [999.,   1.,   0.],
       [  0.,   0.,   0.]])