In [1]:
import pandas as pd
import numpy as np
from sklearn import preprocessing

In [2]:
a = np.random.randint(10, size=(10,1))
b = np.random.randint(50, 100, size=(10,1))
c = np.random.randint(500, 700, size=(10,1))
X = np.concatenate((a, b, c), axis=1)
X

array([[  4,  75, 585],
       [  4,  57, 692],
       [  3,  51, 617],
       [  4,  87, 561],
       [  9,  91, 606],
       [  6,  63, 614],
       [  9,  69, 565],
       [  0,  89, 546],
       [  8,  67, 541],
       [  3,  58, 676]])

In [3]:
X.mean(axis=0)

array([  5. ,  70.7, 600.3])

In [4]:
X.std(axis=0)

array([ 2.79284801, 13.57976436, 49.12036238])

In [5]:
sc = preprocessing.StandardScaler().fit(X)

In [6]:
X_Standardized = sc.transform(X)
X_Standardized

array([[-0.35805744,  0.31664762, -0.31147979],
       [-0.35805744, -1.00885403,  1.86684291],
       [-0.71611487, -1.45068791,  0.33998121],
       [-0.35805744,  1.20031538, -0.80007553],
       [ 1.43222975,  1.4948713 ,  0.11604149],
       [ 0.35805744, -0.56702015,  0.27890674],
       [ 1.43222975, -0.12518627, -0.71864291],
       [-1.79028719,  1.34759334, -1.10544787],
       [ 1.07417231, -0.27246423, -1.20723865],
       [-0.71611487, -0.93521505,  1.54111241]])

In [7]:
X_Standardized.mean(axis=0)

array([ 1.11022302e-17, -2.22044605e-16,  9.10382880e-16])

In [8]:
X_Standardized.std(axis=0)

array([1., 1., 1.])

In [9]:
mn_scaler = preprocessing.MinMaxScaler() #in this values come between 0 to 1

In [10]:
X_scaled = mn_scaler.fit_transform(X)
X_scaled

array([[0.44444444, 0.6       , 0.29139073],
       [0.44444444, 0.15      , 1.        ],
       [0.33333333, 0.        , 0.50331126],
       [0.44444444, 0.9       , 0.13245033],
       [1.        , 1.        , 0.43046358],
       [0.66666667, 0.3       , 0.48344371],
       [1.        , 0.45      , 0.1589404 ],
       [0.        , 0.95      , 0.03311258],
       [0.88888889, 0.4       , 0.        ],
       [0.33333333, 0.175     , 0.89403974]])

In [11]:
mn_scaler1 = preprocessing.MinMaxScaler(feature_range=(0,10)) #in this values come between 0 to 10
X_scaled1 = mn_scaler1.fit_transform(X)
X_scaled1

array([[ 4.44444444,  6.        ,  2.91390728],
       [ 4.44444444,  1.5       , 10.        ],
       [ 3.33333333,  0.        ,  5.03311258],
       [ 4.44444444,  9.        ,  1.32450331],
       [10.        , 10.        ,  4.30463576],
       [ 6.66666667,  3.        ,  4.83443709],
       [10.        ,  4.5       ,  1.58940397],
       [ 0.        ,  9.5       ,  0.33112583],
       [ 8.88888889,  4.        ,  0.        ],
       [ 3.33333333,  1.75      ,  8.94039735]])

In [12]:
X_new = np.append(X, np.array([[70,700,2000]]),axis=0)

In [13]:
X_new

array([[   4,   75,  585],
       [   4,   57,  692],
       [   3,   51,  617],
       [   4,   87,  561],
       [   9,   91,  606],
       [   6,   63,  614],
       [   9,   69,  565],
       [   0,   89,  546],
       [   8,   67,  541],
       [   3,   58,  676],
       [  70,  700, 2000]])

In [14]:
X_new_mn = mn_scaler.fit_transform(X_new)
X_new_mn

array([[0.05714286, 0.03697997, 0.03015764],
       [0.05714286, 0.00924499, 0.10349554],
       [0.04285714, 0.        , 0.05209047],
       [0.05714286, 0.05546995, 0.01370802],
       [0.12857143, 0.06163328, 0.04455106],
       [0.08571429, 0.01848998, 0.05003427],
       [0.12857143, 0.02773498, 0.01644962],
       [0.        , 0.05855162, 0.003427  ],
       [0.11428571, 0.02465331, 0.        ],
       [0.04285714, 0.01078582, 0.09252913],
       [1.        , 1.        , 1.        ]])

In [15]:
r_scaler = preprocessing.RobustScaler()

In [16]:
X_new_rs = r_scaler.fit_transform(X_new)

In [17]:
X_new_rs

array([[ 0.        ,  0.21818182, -0.25149701],
       [ 0.        , -0.43636364,  1.02994012],
       [-0.2       , -0.65454545,  0.13173653],
       [ 0.        ,  0.65454545, -0.53892216],
       [ 1.        ,  0.8       ,  0.        ],
       [ 0.4       , -0.21818182,  0.09580838],
       [ 1.        ,  0.        , -0.49101796],
       [-0.8       ,  0.72727273, -0.71856287],
       [ 0.8       , -0.07272727, -0.77844311],
       [-0.2       , -0.4       ,  0.83832335],
       [13.2       , 22.94545455, 16.69461078]])

In [18]:
X_normalized = preprocessing.normalize(X, norm='l2')
X_normalized

array([[0.00678194, 0.12716139, 0.99185885],
       [0.00576074, 0.08209056, 0.99660822],
       [0.00484565, 0.08237612, 0.99658953],
       [0.00704573, 0.15324456, 0.98816318],
       [0.01468523, 0.14848403, 0.98880576],
       [0.00972049, 0.10206515, 0.99473022],
       [0.01580975, 0.12120811, 0.99250121],
       [0.        , 0.16088036, 0.98697391],
       [0.01467374, 0.12289255, 0.99231149],
       [0.00442158, 0.08548391, 0.99632974]])